export type Product = {
  title: string;
  image: string;
  price?: string;
  rating?: number;
  category: string;
  buttonText?: string;
  isTopup?: boolean;
  isSubscription?: boolean;
  route?: string;
  popular?: boolean;
};

export const mobileGames: Product[] = [
  {
    title: "Mobile Legends",
    image: "/products/mobile-games/mobile-legends.avif",
    price: "299",
    rating: 5,
    category: "MOBA",
    buttonText: "Buy Diamonds",
    route: "/mobile-games/mobile-legends",
  },
  {
    title: "Call of Duty Mobile",
    image: "/products/mobile-games/cod-mobile.avif",
    price: "399",
    rating: 5,
    category: "Action",
    buttonText: "Buy CP",
    route: "/mobile-games/cod-mobile",
  },
  {
    title: "PUBG Mobile",
    image: "/products/mobile-games/pubg-mobile.avif",
    price: "499",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy UC",
    route: "/mobile-games/pubg-mobile",
    popular: true,
  },
  {
    title: "Free Fire",
    image: "/products/mobile-games/free-fire.avif",
    price: "199",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy Diamonds",
    route: "/mobile-games/free-fire",
    popular: true,
  },
  {
    title: "Delta Force",
    image: "/products/mobile-games/delta-force.avif",
    price: "599",
    rating: 5,
    category: "Action",
    buttonText: "Buy Credits",
    route: "/mobile-games/delta-force",
  },
  {
    title: "Blood Strike",
    image: "/products/mobile-games/blood-strike.avif",
    price: "349",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gold",
    route: "/mobile-games/blood-strike",
  },
  {
    title: "Clash of Clans",
    image: "/products/mobile-games/clash-of-clans.avif",
    price: "299",
    rating: 5,
    category: "Strategy",
    buttonText: "Buy Gems",
    route: "/mobile-games/clash-of-clans",
  },
  {
    title: "Clash Royale",
    image: "/products/mobile-games/clash-royale.avif",
    price: "399",
    rating: 5,
    category: "Strategy",
    buttonText: "Buy Gems",
    route: "/mobile-games/clash-royale",
  },
  {
    title: "Brawl Stars",
    image: "/products/mobile-games/brawl-stars.avif",
    price: "299",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gems",
    route: "/mobile-games/brawl-stars",
  },
  {
    title: "Standoff 2",
    image: "/products/mobile-games/standoff-2.avif",
    price: "449",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gold",
    route: "/mobile-games/standoff-2",
  },
  {
    title: "Genshin Impact",
    image: "/products/mobile-games/genshin-impact.avif",
    price: "799",
    rating: 5,
    category: "RPG",
    buttonText: "Buy Primogems",
    route: "/mobile-games/genshin-impact",
  },
  {
    title: "Wuthering Waves",
    image: "/products/mobile-games/wuthering-waves.avif",
    price: "699",
    rating: 5,
    category: "RPG",
    buttonText: "Buy Lunite",
    route: "/mobile-games/wuthering-waves",
  },
  {
    title: "Roblox",
    image: "/products/mobile-games/roblox.avif",
    price: "399",
    rating: 5,
    category: "Sandbox",
    buttonText: "Buy Robux",
    route: "/mobile-games/roblox",
  },
  {
    title: "eFootball",
    image: "/products/mobile-games/efootball.avif",
    price: "599",
    rating: 5,
    category: "Sports",
    buttonText: "Buy Coins",
    route: "/mobile-games/efootball",
  },
  {
    title: "FIFA Mobile",
    image: "/products/mobile-games/fifa-mobile.avif",
    price: "699",
    rating: 5,
    category: "Sports",
    buttonText: "Buy Points",
    route: "/mobile-games/fifa-mobile",
  },
];

export const pcGames : Product[] = [
  {
    title: "Valorant",
    image: "/products/valorant.png",
    price: "799",
    rating: 5,
    category: "FPS",
    buttonText: "Buy VP",
    route: "/pc-games/valorant",
    popular: true,
  },
  {
    title: "Apex Legends",
    image: "/products/apex-legends.png",
    price: "899",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy Coins",
  },
];

export const giftCards: Product[] = [
  {
    title: "Google Play",
    image: "/products/gift-cards/google-play.avif",
    price: "500",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/google-play",
    popular: true,
  },
  {
    title: "Apple Gift Card",
    image: "/products/gift-cards/apple-music.avif",
    price: "1000",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/itunes",
  },
  {
    title: "Steam Wallet",
    image: "/products/gift-cards/steam.avif",
    price: "1500",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/steam-wallet",
  },
  {
    title: "PlayStation",
    image: "/products/gift-cards/playstation.avif",
    price: "2000",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/playstation",
  },
  {
    title: "Valorant Gift Cards",
    image: "/products/gift-cards/valorant.avif",
    price: "1200",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/valorant",
  },
  {
    title: "Amazon Gift Cards",
    image: "/products/gift-cards/amazon.avif",
    price: "1500",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/amazon",
    popular: true,
  },
  {
    title: "GameStop Gift Card",
    image: "/products/gift-cards/game-stop.avif",
    price: "1800",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/gamestop",
  },
  {
    title: "Discord Nitro",
    image: "/products/gift-cards/discord-nitro.avif",
    price: "1200",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/discord-nitro",
  },
  {
    title: "Roblox Gift Cards",
    image: "/products/gift-cards/roblox.avif",
    price: "800",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/roblox",
  },
  {
    title: "Spotify Gift Card",
    image: "/products/gift-cards/spotify.avif",
    price: "600",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/spotify",
    popular: true,
  },
];

export const aiTools: Product[] = [
  {
    title: "ChatGPT Premium",
    image: "/products/ai-tools/chatgpt.avif",
    price: "1999",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    route: "/ai-tools/chatgpt",
    popular: true,
  },
  {
    title: "Perplexity Premium",
    image: "/products/ai-tools/prop-ai.avif",
    price: "1599",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    route: "/ai-tools/proplexity",
  },
  {
    title: "Claude Premium",
    image: "/products/ai-tools/claude-ai.avif",
    price: "1799",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    popular: true,
    route: "/ai-tools/claude",
  },
  {
    title: "Grok Premium",
    image: "/products/ai-tools/grok-ai.avif",
    price: "1299",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    route: "/ai-tools/grok",
  },
  {
    title: "Gemini Premium",
    image: "/products/ai-tools/gemini-ai.avif",
    price: "1899",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    popular: true,
    route: "/ai-tools/gemini",
  },
  {
    title: "GitHub Pro",
    image: "/products/ai-tools/github-pro.avif",
    price: "999",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
    popular: true,
    route: "/ai-tools/github",
  },
  {
    title: "Cursor IDE",
    image: "/products/ai-tools/cursor-ide.avif",
    price: "1499",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
    popular: true,
    route: "/ai-tools/cursor",
  },
  {
    title: "Windsurf IDE",
    image: "/products/ai-tools/windsurf.avif",
    price: "1299",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
    route: "/ai-tools/windsurf",
  },
];

export const subscriptions: Product[] = [
  // Entertainment
  {
    title: "Netflix",
    image: "/products/subscriptions/netflix.avif",
    price: "1499",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/netflix",
    popular: true,
  },
  {
    title: "Hulu",
    image: "/products/subscriptions/hulu.avif",
    price: "899",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/hulu",
  },
  {
    title: "Amazon Prime",
    image: "/products/subscriptions/amazon-prime.avif",
    price: "1299",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/amazon-prime",
  },
  {
    title: "Disney Plus",
    image: "/products/subscriptions/disney.avif",
    price: "999",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/disney-plus",
    popular: true,
  },
  {
    title: "ZEE5",
    image: "/products/subscriptions/zee5.avif",
    price: "599",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/zee5",
  },
  {
    title: "Sony Liv",
    image: "/products/subscriptions/sony-liv.avif",
    price: "699",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/SonyLiv",
  },
  {
    title: "Ullu Premium",
    image: "/products/subscriptions/ullu.avif",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/ullu",
  },
  {
    title: "Alt Balaji",
    image: "/products/subscriptions/alt-balaji.avif",
    price: "499",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/alt-balaji",
  },
  {
    title: "HBO Max",
    image: "/products/subscriptions/hbo.avif",
    price: "1199",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/hbo-max",
  },
  {
    title: "Apple TV",
    image: "/products/subscriptions/apple-tv.avif",
    price: "799",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/apple-tv",
  },
  {
    title: "YouTube Premium",
    image: "/products/subscriptions/yt-premium.avif",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/youtube-premium",
  },
  {
    title: "Apple Music",
    image: "/products/subscriptions/apple-music.avif",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/apple-music",
  },
  {
    title: "Crunchyroll",
    image: "/products/subscriptions/crunchy.avif",
    price: "799",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/crunchyroll",
  },
  {
    title: "Spotify Premium",
    image: "/products/subscriptions/spotify.avif",
    price: "299",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/spotify",
  },
  // Gaming
  {
    title: "Xbox Game Pass",
    image: "/products/subscriptions/x-box.avif",
    price: "1299",
    rating: 5,
    category: "Gaming",
    buttonText: "Subscribe",
    route: "/subscriptions/xbox-game-pass",
  },
  {
    title: "Ubisoft+",
    image: "/products/subscriptions/ubisoft.avif",
    price: "1599",
    rating: 5,
    category: "Gaming",
    buttonText: "Subscribe",
    route: "/subscriptions/ubisoft-plus",
  },
  // Productivity
 
];

export const productivity: Product[] = [
   {
    title: "Canva Pro",
    image: "/products/others/canva.avif",
    price: "1299",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/canva-pro",
    popular: true,
  },
  {
    title: "Duolingo Plus",
    image: "/products/others/duolingo.avif",
    price: "899",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/duolingo",
  },
  {
    title: "Quillbot",
    image: "/products/others/quillbot.avif",
    price: "599",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/quillbot",
  },
  {
    title: "Grammarly",
    image: "/products/others/grammarly.avif",
    price: "1199",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/grammarly",
  },
  {
    title: "Office 365",
    image: "/products/others/office365.avif",
    price: "1999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/office-365",
  },
  {
    title: "Google One",
    image: "/products/others/google-one.avif",
    price: "699",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/google-one",
  },
  {
    title: "Capcut Pro",
    image: "/products/others/capcut.avif",
    price: "799",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/capcut-pro",
  },
  {
    title: "Figma Pro",
    image: "/products/others/figma.avif",
    price: "1499",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/figma-pro",
  },
  {
    title: "Notion Pro",
    image: "/products/others/notion.avif",
    price: "999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/notion-pro",
  },
  {
    title: "Zoom Pro",
    image: "/products/others/zoom.avif",
    price: "1299",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/zoom-pro",
  },
  {
    title: "iCloud+",
    image: "/products/others/icloud.avif",
    price: "399",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/icloud-plus",
  },
  {
    title: "CodePen Pro",
    image: "/products/others/codepen.avif",
    price: "899",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    route: "/subscriptions/codepen-pro",
  },

  // Security & VPN
  {
    title: "NordVPN",
    image: "/products/others/nordvpn.avif",
    price: "899",
    rating: 5,
    category: "Security",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/nordvpn",
  },
  {
    title: "ExpressVPN",
    image: "/products/others/expressvpn.avif",
    price: "1299",
    rating: 5,
    category: "Security",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/expressvpn",
  },
  // Social
  {
    title: "Tinder Plus",
    image: "/products/others/tinder.avif",
    price: "799",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/tinder-plus",
  },
  {
    title: "Bumble Plus",
    image: "/products/others/bumble.avif",
    price: "899",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/bumble-plus",
  },
  {
    title: "Telegram Stars",
    image: "/products/others/telegram-stars.avif",
    price: "299",
    rating: 5,
    category: "Social",
    buttonText: "Buy Stars",
    popular: true,
    route: "/subscriptions/telegram-stars",
  },
  {
    title: "Discord Nitro",
    image: "/products/others/nitro.avif",
    price: "999",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
    route: "/gift-cards/discord-nitro",
  },
  {
    title: "LinkedIn Premium",
    image: "/products/others/linkedin.avif",
    price: "1599",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
    route: "/subscriptions/linkedin",
  },
];

