export type Product = {
  title: string;
  image: string;
  price?: string;
  rating?: number;
  category: string;
  buttonText?: string;
  isTopup?: boolean;
  isSubscription?: boolean;
  route?: string;
  popular?: boolean;
};

export const mobileGames: Product[] = [
  {
    title: "Mobile Legends",
    image: "/products/mobile-legends.png",
    price: "299",
    rating: 5,
    category: "MOBA",
    buttonText: "Buy Diamonds",
    route: "/mobile-games/mobile-legends",
  },
  {
    title: "Call of Duty Mobile",
    image: "/products/cod-mobile.png",
    price: "399",
    rating: 5,
    category: "Action",
    buttonText: "Buy CP",
    route: "/mobile-games/call-of-duty-mobile",
  },
  {
    title: "PUBG Mobile",
    image: "/products/pubg-mobile.png",
    price: "499",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy UC",
    route: "/mobile-games/pubg-mobile",
    popular: true,
  },
  {
    title: "Free Fire",
    image: "/products/free-fire.png",
    price: "199",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy Diamonds",
    route: "/mobile-games/free-fire",
    popular: true,
  },
  {
    title: "Delta Force",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Action",
    buttonText: "Buy Credits",
  },
  {
    title: "Blood Strike",
    image: "/placeholder.svg",
    price: "349",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gold",
  },
  {
    title: "Clash of Clans",
    image: "/placeholder.svg",
    price: "299",
    rating: 5,
    category: "Strategy",
    buttonText: "Buy Gems",
  },
  {
    title: "Clash Royale",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Strategy",
    buttonText: "Buy Gems",
  },
  {
    title: "Brawl Stars",
    image: "/placeholder.svg",
    price: "299",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gems",
  },
  {
    title: "Standoff 2",
    image: "/placeholder.svg",
    price: "449",
    rating: 5,
    category: "Action",
    buttonText: "Buy Gold",
  },
  {
    title: "Genshin Impact",
    image: "/placeholder.svg",
    price: "799",
    rating: 5,
    category: "RPG",
    buttonText: "Buy Primogems",
  },
  {
    title: "Wuthering Waves",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "RPG",
    buttonText: "Buy Lunite",
  },
  {
    title: "Roblox",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Sandbox",
    buttonText: "Buy Robux",
  },
  {
    title: "eFootball",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Sports",
    buttonText: "Buy Coins",
  },
  {
    title: "FIFA Mobile",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "Sports",
    buttonText: "Buy Points",
  },
];

export const pcGames : Product[] = [
  {
    title: "Valorant",
    image: "/products/valorant.png",
    price: "799",
    rating: 5,
    category: "FPS",
    buttonText: "Buy VP",
    route: "/pc-games/valorant",
    popular: true,
  },
  {
    title: "Apex Legends",
    image: "/products/apex-legends.png",
    price: "899",
    rating: 5,
    category: "Battle Royale",
    buttonText: "Buy Coins",
  },
];

export const giftCards: Product[] = [
  {
    title: "Google Play",
    image: "/products/google-play.png",
    price: "500",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    popular: true,
  },
  {
    title: "iTunes",
    image: "/products/itunes.png",
    price: "1000",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "Steam Wallet",
    image: "/products/steam-wallet.png",
    price: "1500",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
    route: "/gift-cards/steam-wallet",
  },
  {
    title: "PlayStation",
    image: "/products/playstation.png",
    price: "2000",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "Valorant Gift Cards",
    image: "/products/valorant.png",
    price: "1200",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "Roblox Gift Cards",
    image: "/placeholder.svg",
    price: "800",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "Minecraft Minecoins",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "Fortnite V-Bucks",
    image: "/placeholder.svg",
    price: "999",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
  {
    title: "AWS Credits",
    image: "/placeholder.svg",
    price: "2999",
    rating: 5,
    category: "Gift Cards",
    buttonText: "Buy Now",
  },
];

export const aiTools: Product[] = [
  {
    title: "ChatGPT Premium",
    image: "/products/chatgpt.png",
    price: "1999",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    route: "/ai-tools/chatgpt",
    popular: true,
  },
  {
    title: "Perplexity Premium",
    image: "/products/prop-ai.png",
    price: "1599",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
  },
  {
    title: "Claude Premium",
    image: "/products/claude-ai.png",
    price: "1799",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Super Grok Premium",
    image: "/products/grok-ai.png",
    price: "1299",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
  },
  {
    title: "Gemini Premium",
    image: "/placeholder.svg",
    price: "1899",
    rating: 5,
    category: "AI Assistant",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "GitHub Copilot",
    image: "/placeholder.svg",
    price: "999",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Cursor IDE",
    image: "/placeholder.svg",
    price: "1499",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Windsurf IDE",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "AI Coding",
    buttonText: "Subscribe",
  },
];

export const subscriptions: Product[] = [
  // Entertainment
  {
    title: "Netflix",
    image: "/products/netflix.png",
    price: "1499",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    route: "/subscriptions/netflix",
    popular: true,
  },
  {
    title: "Hulu",
    image: "/products/hulu.png",
    price: "899",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Amazon Prime",
    image: "/products/amazon-prime.png",
    price: "1299",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Disney Plus",
    image: "/products/disney.png",
    price: "999",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "ZEE5",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Hotstar",
    image: "/placeholder.svg",
    price: "1499",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Sony Live",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Ullu",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Alt Balaji",
    image: "/placeholder.svg",
    price: "499",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "HBO Max",
    image: "/placeholder.svg",
    price: "1199",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Apple TV",
    image: "/placeholder.svg",
    price: "799",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "YouTube Premium",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Apple Music",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "SoundCloud Pro",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Twitch Turbo",
    image: "/placeholder.svg",
    price: "899",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Crunchyroll",
    image: "/placeholder.svg",
    price: "799",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Voot",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  {
    title: "Hoichoi",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Spotify",
    image: "/placeholder.svg",
    price: "299",
    rating: 5,
    category: "Entertainment",
    buttonText: "Subscribe",
  },
  // Gaming
  {
    title: "Xbox Game Pass",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "Gaming",
    buttonText: "Subscribe",
  },
  {
    title: "Ubisoft+",
    image: "/placeholder.svg",
    price: "1599",
    rating: 5,
    category: "Gaming",
    buttonText: "Subscribe",
  },
  // Productivity
  {
    title: "Canva Pro",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Duolingo",
    image: "/placeholder.svg",
    price: "899",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "QuillBot",
    image: "/placeholder.svg",
    price: "599",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Grammarly",
    image: "/placeholder.svg",
    price: "1199",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Office 365",
    image: "/placeholder.svg",
    price: "1999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Google One",
    image: "/placeholder.svg",
    price: "699",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "CapCut Pro",
    image: "/placeholder.svg",
    price: "799",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Figma Professional",
    image: "/placeholder.svg",
    price: "1499",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Notion Pro",
    image: "/placeholder.svg",
    price: "999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "Zoom Pro",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "Microsoft Teams",
    image: "/placeholder.svg",
    price: "1199",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "iCloud+",
    image: "/placeholder.svg",
    price: "399",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "GitHub Pro",
    image: "/placeholder.svg",
    price: "999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "CodePen Pro",
    image: "/placeholder.svg",
    price: "899",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "Visual Studio Professional",
    image: "/placeholder.svg",
    price: "2999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  {
    title: "Vercel Pro",
    image: "/placeholder.svg",
    price: "1999",
    rating: 5,
    category: "Productivity",
    buttonText: "Subscribe",
  },
  // Security & VPN
  {
    title: "NordVPN",
    image: "/placeholder.svg",
    price: "899",
    rating: 5,
    category: "Security",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "ExpressVPN",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "Security",
    buttonText: "Subscribe",
  },
  // Social
  {
    title: "Tinder Plus",
    image: "/placeholder.svg",
    price: "799",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Bumble Plus",
    image: "/placeholder.svg",
    price: "899",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "Telegram Stars",
    image: "/placeholder.svg",
    price: "299",
    rating: 5,
    category: "Social",
    buttonText: "Buy Stars",
    popular: true,
  },
  {
    title: "Discord Nitro",
    image: "/placeholder.svg",
    price: "999",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
  },
  {
    title: "LinkedIn Pro",
    image: "/placeholder.svg",
    price: "1599",
    rating: 5,
    category: "Social",
    buttonText: "Subscribe",
    popular: true,
  },
];

export const topUpCards: Product[] = [
  {
    title: "Mobile Legends",
    image: "/products/mobile-legends.png",
    price: "399",
    rating: 5,
    category: "Mobile Games",
    buttonText: "Top Up",
    isTopup: true,
    route: "/mobile-games/mobile-legends",
  },
  {
    title: "PUBG Mobile UC/Passes",
    image: "/products/pubg-mobile.png",
    price: "999",
    rating: 5,
    category: "Mobile Games",
    buttonText: "Top Up",
    isTopup: true,
    route: "/mobile-games/pubg-mobile",
  },
  {
    title: "Steam Wallet",
    image: "/products/steam-wallet.png",
    price: "1000",
    rating: 5,
    category: "PC Games",
    buttonText: "Top Up",
    isTopup: true,
    route: "/gift-cards/steam-wallet",
  },
  {
    title: "Valorant Points",
    image: "/products/valorant.png",
    price: "799",
    rating: 5,
    category: "PC Games",
    buttonText: "Top Up",
    isTopup: true,
  },
  {
    title: "Free Fire",
    image: "/products/free-fire.png",
    price: "299",
    rating: 5,
    category: "Mobile Games",
    buttonText: "Top Up",
    isTopup: true,
  },
  {
    title: "Genshin Impact",
    image: "/placeholder.svg",
    price: "1299",
    rating: 5,
    category: "Mobile Games",
    buttonText: "Top Up",
    isTopup: true,
  },
];
